//
//  CalculateExchangeRateModels.swift
//  Currencies
//
//  Created by Jakub Hutny on 14.12.2016.
//  Copyright (c) 2016 Jakub Hutny. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct CalculateExchangeRate
{
    struct FetchCurrencies {
        struct Request {
            
        }
        struct Response {
            var currencies: [Currency]
            var date: String
        }
        struct ViewModel {
            struct DisplayedCurrency {
                var name: String
            }
            var date: String
            var displayedCurrencies: [DisplayedCurrency]
        }
    }
    
    struct InputLabel {
        struct Request {
            
        }
        struct Response {
            var name: String
        }
        struct ViewModel {
            var name: String
        }
    }
    
    struct OutputLabel {
        struct Request {
            
        }
        struct Response {
            var name: String
        }
        struct ViewModel {
            var name: String
        }
    }
    
    struct ResultLabel {
        struct Request {
            var isOnStart: Bool
            var amount: String
            var inputCurrency: String
            var outputCurrency: String
            
            init(isOnStart: Bool) {
                self.isOnStart = isOnStart
                self.amount = ""
                self.inputCurrency = ""
                self.outputCurrency = ""
            }
            
            init(amount: String, inputCurrency: String, outputCurrency: String) {
                self.isOnStart = false
                self.amount = amount
                self.inputCurrency = inputCurrency
                self.outputCurrency = outputCurrency
            }
            
            init(isOnStart: Bool, amount: String, inputCurrency: String, outputCurrency: String) {
                self.isOnStart = isOnStart
                self.amount = amount
                self.inputCurrency = inputCurrency
                self.outputCurrency = outputCurrency
            }
        }
        struct Response {
            var result: Double
        }
        struct ViewModel {
            var name: String
        }
    }
}

