//
//  CalculateExchangeRateWorkerTests.swift
//  Currencies
//
//  Created by Jakub Hutny on 14.12.2016.
//  Copyright (c) 2016 Jakub Hutny. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import Currencies
import XCTest

class CalculateExchangeRateWorkerTests: XCTestCase
{
    // MARK: - Subject under test
  
    var sut: CalculateExchangeRateWorker!
  
    // MARK: - Test lifecycle
  
    override func setUp()
    {
        super.setUp()
        setupCalculateExchangeRateWorker()
    }
  
    override func tearDown()
    {
        super.tearDown()
    }
  
    // MARK: - Test setup
  
    func setupCalculateExchangeRateWorker()
    {
        sut = CalculateExchangeRateWorker()
    }
  
    // MARK: - Test doubles
  
    // MARK: - Tests
    
    func testShouldReturnZeroResultWhenOnStart() {
        // Given
        let isOnStart = true
        let expectedResult = 0.00
        
        // When
        let result = sut.calculateResult(isOnStart: isOnStart)
        
        // Then
        XCTAssertEqual(result, expectedResult, "Result is " + String(result) + " when expected to be " + String(expectedResult))
    }
    
    func testShouldCalculateResultWhenNotOnStart() {
        // Given
        let isOnStart = false
        let inputRate = 2.0
        let outputRate = 4.0
        let amount = 5.0
        let expectedResult = 10.0
        
        // When
        let result = sut.calculateResult(isOnStart: isOnStart, inputRate: inputRate, outputRate: outputRate, amount: amount)
        
        // Then
        XCTAssertEqual(result, expectedResult)
    }

}
